Repository stefanpenner/broccoli-concat-analyser, pull requests merged in 2020-10, with the labels that each got.

#54 Drop node 6/8 support
  .eslintignore
  .eslintrc.js
  .travis.yml
  package.json
  yarn.lock
Labels: breaking

#55 Update terser to fix problems using latest ECMAScript features
  lib/summarize.js
  package.json
  test/acceptance/__snapshots__/cli.test.js.snap
  test/integration/__snapshots__/summarize.test.js.snap
  yarn.lock
Labels: bug

#57 Setup release-it
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#58 Fix release-it dependencies
  package.json
  yarn.lock
Labels: internal
